# Generated by Django 2.1 on 2018-11-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccid', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cs_users',
                'managed': False,
            },
        ),
    ]
