# Generated by Django 2.1 on 2018-12-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_iptable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csusers',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
