# Generated by Django 2.1 on 2019-01-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181201_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csusers',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
