# Generated by Django 2.0.3 on 2019-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'cs_packages',
                'managed': False,
            },
        ),
    ]
