# Generated by Django 2.0.3 on 2019-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'admin_users',
                'managed': False,
            },
        ),
    ]
