# Generated by Django 2.1 on 2018-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('auth_user', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('up', 'up'), ('down', 'down')], default='up', max_length=4)),
            ],
            options={
                'managed': False,
                'db_table': 'cs_domains',
            },
        ),
    ]
