# Generated by Django 2.1 on 2018-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('initiator_id', models.IntegerField(blank=True, null=True)),
                ('initiator_type', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=5)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, default='0.00', null=True)),
                ('amount', models.FloatField(blank=True, default='0.00', null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='0', max_length=1)),
                ('response', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('initiated_at',),
                'managed': False,
                'db_table': 'cs_orders',
            },
        ),
    ]
